### ISSUE TITLE
Keeps on loading forever

### ISSUE THREAD

**Issue by seffs** [cinnyapp/cinny-desktop#134]
### Describe the bug

After installation, Cinny can't connect to any server. It gets stuck in "Connecting to ..."

### Reproduction

1. Fresh install
2. Open Cinny
3. Select any server
4. Wait for connection to be established

### Expected behavior

Cinny should connect to at least one of the servers

### Platform and versions

```shell
1. MacOS 10.14.6 (Mojave)
2. Cinny version: 2.2.2
3. Matrix homeserver: All of them
4. Downloaded from: Github
```

**Comment by kfiven** [comment]
Could you look for error in `Right click > Inspect > Console`?

**Comment by seffs** [comment]
![image](https://user-images.githubusercontent.com/46768740/212471469-7bd5c335-d04b-436e-95bf-1a4131dd2c02.png)

**Comment by kfiven** [comment]
@seffs the oldest version Tauri "support" is mojave 10.15.

**Comment by kfiven** [comment]
this seems something related to that.

**Comment by seffs** [comment]
Confirmed. It needs at least 10.15. Maybe a little disclaimer on the README will help future visitors. Thanks for looking into it.
