### ISSUE TITLE
Ability to install using `winget` (windows package manager)

### ISSUE THREAD

**Issue by m1karii** [cinnyapp/cinny-desktop#163]
### Describe the problem

currently i cannot install cinny using CLI only on windows

### Describe the solution you'd like

i d like to be able to install cinny using `winget` package manager

**Comment by superusercode** [comment]
closes with https://github.com/microsoft/winget-pkgs/pull/110000

**Comment by kfiven** [comment]
@superusercode does that also handle the installation of edge webview if it's not installed already?

**Comment by superusercode** [comment]
@kfiven on the platforms where winget is available, webview2 is expected to be installed. The PR was accepted and cinny is now available via winget:
![image](https://github.com/cinnyapp/cinny-desktop/assets/60588434/ca0446e6-0417-4040-9422-dd3781af6434)
