### ISSUE TITLE
Voice message

### ISSUE THREAD

**Issue by sim6** [cinnyapp/cinny-desktop#168]
### Describe the problem

Isn't easy to send a voice message. I need to record it via another app and send as a file.

### Describe the solution you'd like

Add a integrated voice message send feature.

**Comment by kfiven** [comment]
Duplicate of https://github.com/cinnyapp/cinny/issues/632

**Comment by sim6** [comment]
Sorry, I not found the original issue. :(

**Comment by sim6** [comment]
Is cinny-desktop a wrapper of cinny?
