### ISSUE TITLE
Run multiple instances of Cinny to use different homeservers?

### ISSUE THREAD

**Issue by photex** [cinnyapp/cinny-desktop#180]
### Describe the problem

Howdy!

I've got my matrix.org account, but I recently joined another homeserver that isn't interested in federation. So currently it isn't possible for me to use them both with Cinny at the same time.
This  seems like a common limitation of most matrix clients and I'm not sure why. 

### Describe the solution you'd like

I'm curious about is whether it's possible to support "profiles" with the desktop app which would amount to running two copies of it, each using a different connection.
Since I'm ignorant of the technicalities involved I realize that it might not be simpler than adding support for multiple connections in the cinny app itself instead.

**Comment by jivanpal** [comment]
This is being tracked here: https://github.com/cinnyapp/cinny/issues/66

**Comment by kfiven** [comment]
Closing as duplicate.
