### ISSUE TITLE
remove/disable installing microsoft edge via the msi installer

### ISSUE THREAD

**Issue by c33s** [cinnyapp/cinny-desktop#187]
### Describe the problem

installing cinny-desktop via msi also tries to run microsoftedgeupdate.exe in background.

### Describe the solution you'd like

please remove this silent install of microsoft edge or at least make a checkbox for it.

**Comment by c33s** [comment]
as the app instantly closes after starting is assume edge is a requirement for cinny to run, is it?

**Comment by kfiven** [comment]
It is requirement, that's how Tauri works, it need the OS's default webview to work. Btw it's installing edge webview.

**Comment by c33s** [comment]
:(

hoped for an internal chromium. thanks for the clearification
