### ISSUE TITLE
Zoom Images

### ISSUE THREAD

**Issue by Anaphylaxis** [cinnyapp/cinny-desktop#195]
### Describe the problem

In Element there is a magnifying glass you can use to zoom and pan around images. Cinny currently just fits it to the screen but it makes text unreadable, meaning the image has to be saved, causing extra workflow steps

### Describe the solution you'd like

Click an image in a chat to zoom, then click+drag to pan. Would be nice to zoom in+out incrementally with the scroll wheel.

**Comment by kfiven** [comment]
Should be fixed in v3.
