### ISSUE TITLE
Weird "New messages" divider behaviour

### ISSUE THREAD

**Issue by gardenerik** [cinnyapp/cinny-desktop#208]
### Describe the bug

When I send a message to a room, the "New messages" divider appears even though I did send that message, so it is not really "New".

![image](https://github.com/cinnyapp/cinny/assets/11409143/105ba38b-b028-40a0-bb80-4308b281713e)

Also, I did not figure out how to get rid of that divider differently than closing and opening the room again.

### Reproduction

1. Send a message
2. "New messages" appear

### Expected behavior

1. Send a message
2. No "New messages" appears

### Platform and versions

```shell
OS: Linux
Cinny: 2.2.6
Homeserver: self-hosted Synapse
```

**Comment by kfiven** [comment]
Should be fixed with current release v3
