### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by Epenko1337** [cinnyapp/cinny-desktop#209]
### Describe the bug

Unable to start application

### Reproduction

1. Download last windows .msi release
2. Start application

### Expected behavior

Application immediately crashes with error 0x65

### Platform and versions

```shell
1. OS: Windows 10 LTSC IoT, Build: 19044
2. Cinny version: 2.2.6
3. Downloaded from github
```

**Comment by kfiven** [comment]
Do you have Microsoft Edge WebView installed?

**Comment by Epenko1337** [comment]
nope

**Comment by kfiven** [comment]
It requires that otherwise it won't work. I'm closing as it's not Cinny issue. It will work once you install WebView.
