### ISSUE TITLE
Emoticons are no longer displayed

### ISSUE THREAD

**Issue by alexohneander** [cinnyapp/cinny-desktop#214]
### Describe the bug

After updating to v3.0.0, the emoticons are no longer displayed.

![Emoticons-Bug](https://i.imgur.com/my8jdLV.png "No Emoticons")

### Reproduction

1. Click on any Chat
2. Click on Emoticons
3. See nothing

### Expected behavior

That we can see the Emoticons.

### Platform and versions

```shell
1. OS: MacOS Sonoma 14 (ARM)
2. Cinny version: 3.0.0
3. Matrix homeserver: dev-null.rocks
4. Downloaded from: Github
```

### Additional context

I can't see emoticons in normal chats anymore either.

**Comment by kfiven** [comment]
@alexohneander There is some issue with twemoji font rendering on MacOS Sonoma. The fix will have to come from the font library authors. What you could do is enable system emojis from Cinny settings and you'll see your native emojis.

**Comment by alexohneander** [comment]
@kfiven That's great! I had not seen the option. Thanks

**Comment by kfiven** [comment]
We have made the System emojis as default so this is fixed by that on our end.
