### ISSUE TITLE
ensure single instance of Cinny

### ISSUE THREAD

**Issue by camelCaseNick** [cinnyapp/cinny-desktop#235]
### Describe the problem

Since #166, Cinny desktop supports running in background, and displays a tray icon on systems that support this. However, that does not stop you from launching another instance.

### Describe the solution you'd like

Usually, the expected behaviour here is that the new instance brings the already running one to foreground.

### Alternatives considered

Using the task manager of my choice to kill Cinny? No, there is no viable alternative, especially on tray-less systems such as GNOME.

### Additional context

For the inter process communication, there already is the [single instance tauri plugin](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/single-instance).

**Comment by kfiven** [comment]
Duplicate of #210
