### ISSUE TITLE
Version 3.2.1 displays incorrect version in About page

### ISSUE THREAD

**Issue by zellchristensen** [cinnyapp/cinny-desktop#244]
### Describe the bug

The About section for version 3.2.1 displays 3.2.0. 

![2023-11-13_21-17-04](https://github.com/cinnyapp/cinny-desktop/assets/38737447/0e28d3aa-ed52-4946-a0eb-4fbfc6c83571)

### Reproduction

Click your icon on the bottom left
Click About tab

### Expected behavior

Proper version number is displayed.

### Platform and versions

```shell
OS: Windows 7 x64
Cinny version 3.2.1
Matrix homeserver: matrix.org
Downloaded from GitHub via MSI release ( Cinny_desktop-x86_64.msi )
```

### Additional context

I initially thought I mixed up something  or improperly renamed something and re-downloaded both releases from the github and even hashed the files to make sure they are distinct.

The Cinny.exe file from the 3.2.1 release has an MD5 hash of `5EF69916077F356AA1182622CDCDDF7A`.
The Cinny.exe file from the 3.2.0 release has an MD5 hash of `6699E8A1107E2622634F29EF39DD179D`.

Launching the 3.2.0 release with hash `6699E8A1107E2622634F29EF39DD179D` prompts me to download the updated 3.2.1 version.
![2023-11-13_21-17-53](https://github.com/cinnyapp/cinny-desktop/assets/38737447/6828e2ee-008a-484c-847a-69d96131ad8f)

Launching the 3.2.1 release with hash `5EF69916077F356AA1182622CDCDDF7A` does not prompt me at all.

**Comment by kfiven** [comment]
There's no v3.2.1 in real, this was just bumped to fix the flatpak build.

**Comment by kfiven** [comment]
Since we didn't do v3.2.1 in webapp it still shows v3.2.0 in about.
