### ISSUE TITLE
macOS cannot start app 

### ISSUE THREAD

**Issue by ghost** [cinnyapp/cinny-desktop#311]
### Describe the bug

with Version 4.0.1 (20240724.142512) 
I get the notification, that the app is damaged and cannot be launched. 

Using xattr I can get the app to launch and see following Image. 
<img width="400" alt="image" src="https://github.com/user-attachments/assets/279cb887-4c27-4f4e-af31-eb5fbd514c1e">

### Reproduction

each time I try and launch the app. Even when removing all the configuration. 

### Platform and versions

```shell
macOS 14.5 (23F79)
cinny Version 4.0.1 (20240724.142512)
```

**Comment by kyleerhabor** [comment]
I cannot launch v4.0.1 at all since macOS claims the app is built for arm64 (same platform and version).

**Comment by Mistdek** [comment]
A similar problem, how to solve it?

**Comment by Neved4** [comment]
Seems to be fixed by https://github.com/cinnyapp/cinny-desktop/pull/313, try version [v4.0.3](https://github.com/cinnyapp/cinny-desktop/releases/tag/v4.0.3) 🤍

**Comment by ghost** [comment]
thank you, I got everything working again!
