### ISSUE TITLE
Screen size usability

### ISSUE THREAD

**Issue by Neved4** [cinnyapp/cinny-desktop#354]
### Describe the problem

More a discussion than an issue, I’m interested in your thoughts on this one. 

After https://github.com/cinnyapp/cinny-desktop/pull/347/commits/266645a3239e564642fd8ec50e4ddc9a623f4ce9 Cinny's default size is `1280x905`. This seems large compared to the previous one.

I can see that the intent is to make better use of screen real state, and I’m wondering if a different resolution might be better:
1. `1280x905` feels unusual, is there a specific reasoning behind it?
1. A resolution like `1280x720` might align better with common resolutions.  
Cinny initially having smaller size made it feel friendly and minimal, though this might be subjective.
1. After https://github.com/cinnyapp/cinny-desktop/pull/347 Cinny will remember screen size and position,  
so everyone will be able to adjust app size to their personal preference.
1. Default positions like `x: 320`, `y: 160` (Discord's default) could improve initial screen placement,  
as `center` seems to currently bleed through the Dock in macOS.

### Describe the solution you'd like

Maybe we could add these after https://github.com/cinnyapp/cinny-desktop/pull/347:
```jsonc
"windows": [
  {
    "title": "Cinny",
    "width": 1280,
    "height": 720,
    "x": 320,
    "y": 160,
    // ...
  }
]
```

**Comment by kfiven** [comment]
The reason I increased it because on the login screen we had to do the scroll or resize the window to see the all of the options. 

I don't know if it's unusual but all I did is increased the old values by 25%.

Although I think this won't be an issue once we merge #327.

**Comment by Neved4** [comment]
Thanks much for the explanation I understand it now
