### ISSUE TITLE
AppImage shows a blank screen

### ISSUE THREAD

**Issue by Nekothegamer** [cinnyapp/cinny-desktop#368]
### Describe the bug

the officially distributed AppImage does not work, when opened it just shows a blank screen and does nothing else

![Schermata su 2024-10-06 14-28-22](https://github.com/user-attachments/assets/9ba33be8-405c-4db5-a8e9-05b30dd707a0)

### Reproduction

1. download AppImage
2. open it

### Expected behavior

the application should start instead

### Platform and versions

```shell
1. OS: Fedora Workstation 40
2. Cinny version: 4.2.1
3. homeserver: envs.net
4. downloaded from: Github
```

**Comment by ChaosNicro** [comment]
Duplicate of #227
