### ISSUE TITLE
Feature Request: Change cinny instance!

### ISSUE THREAD

**Issue by viasux** [cinnyapp/cinny-desktop#84]
It would be great if you could choose something other than `cinny.in` as your instance on the desktop app!

**Comment by kfiven** [comment]
Where are we choosing cinny.in instance?

**Comment by viasux** [comment]
> Where are we choosing cinny.in instance?

WAIT is it 100% locally run im so dumb

**Comment by kfiven** [comment]
yes it runs locally.
